#!/usr/bin/env bash
# install.sh — user-space install (no sudo)
# Usage:
#   ./scripts/install.sh                     # installs to ~/.local
#   ./scripts/install.sh /custom/prefix /custom/config_prefix      # e.g., /home/user/.local-alt /home/user/.config-alt

set -Eeuo pipefail
IFS=$'\n\t'

# ---------- Config: default to ~/.local ----------
DEFAULT_PREFIX="${HOME}/.local"
DEFAULT_CONFIG_PREFIX="${HOME}/.config"
PREFIX="${1:-$DEFAULT_PREFIX}"
CONFIG_PREFIX="${2:-$DEFAULT_CONFIG_PREFIX}"
BIN_DIR="${PREFIX}/bin"
SHARE_DIR="${PREFIX}/share/smartslurmcommands"
MAN_DIR="${PREFIX}/share/man/man1"
USER_CONFIG_DIR="${CONFIG_PREFIX}/smartslurmcommands"
USER_CONFIG_FILE="$USER_CONFIG_DIR/config"

# ---------- Resolve repo root ----------
_resolve_realpath() {
  local p="$1"
  if command -v readlink >/dev/null 2>&1; then
    # GNU readlink -f (Linux); macOS lacks -f so fall back to Python
    local r
    if r="$(readlink -f "$p" 2>/dev/null)"; then
      printf '%s\n' "$r"
      return 0
    fi
  fi
  python3 - <<'PY' "$p"
import os,sys
print(os.path.realpath(sys.argv[1]))
PY
}
SELF="$(_resolve_realpath "$0")"
ROOT="$(cd "$(dirname "$SELF")/.." && pwd)"

echo "==> Installing smartslurmcommands (user mode)"
echo "    PREFIX   : $PREFIX"
echo "    BIN_DIR  : $BIN_DIR"
echo "    SHARE_DIR: $SHARE_DIR"
echo "    MAN_DIR  : $MAN_DIR"
echo

# ---------- Create dirs ----------
mkdir -p "$BIN_DIR" "$SHARE_DIR" "$MAN_DIR" "$USER_CONFIG_DIR"

# ---------- Create config file --------------
if [[ ! -f "$USER_CONFIG_FILE" ]]; then
  cp "${ROOT}"/config "$USER_CONFIG_FILE"
  echo "==>  Created $USER_CONFIG_FILE"
  echo ""
else
  echo "==>   Found existing $USER_CONFIG_FILE (left untouched)"
  echo ""
fi

# ---------- Copy shared assets to SHARE_DIR ----------
echo "==> Copying shared assets"
# Clean previous install for a fresh state (only our tree)
if [[ -d "$SHARE_DIR" ]]; then
  rm -rf "$SHARE_DIR"
fi
mkdir -p "$SHARE_DIR"
for d in lib cmd etc completions man docs VERSION; do
  [[ -d "$ROOT/$d" ]] && cp -R "$ROOT/$d" "$SHARE_DIR/"
done

# Also copy man pages into per-user man dir for 'man' to find
if [[ -d "$ROOT/man" ]]; then
  echo "==> Installing man pages to $MAN_DIR"
  find "$ROOT/man" -type f -name '*.1' -exec install -m 0644 {} "$MAN_DIR/" \;
fi

# ---------- Install shims into BIN_DIR ----------
echo "==> Installing command shims to $BIN_DIR"
if [[ -d "$ROOT/bin" ]]; then
  for src in "$ROOT"/bin/*; do
    [[ -f "$src" && -x "$src" ]] || continue
    name="$(basename "$src")"
    cat > "$BIN_DIR/$name" <<EOF
#!/usr/bin/env bash
# Installed shim for $name (generated by install.sh)
set -Eeuo pipefail
SSC_HOME="$SHARE_DIR"
exec bash "\$SSC_HOME/cmd/$name/$name.sh" "\$@"
EOF
chmod 0755 "$BIN_DIR/$name"
    echo "  -> $BIN_DIR/$name"
  done
fi

echo
echo "==> Done."

# ---------- Helpful hints ----------
NEED_PATH_HINT=false
case ":${PATH}:" in
  *":${BIN_DIR}:"*) : ;;
  *) NEED_PATH_HINT=true ;;
esac

NEED_MANPATH_HINT=false
# Many systems respect $MANPATH only if set explicitly
if command -v man >/dev/null 2>&1; then
  if ! man -w 2>/dev/null | tr ':' '\n' | grep -q "^${PREFIX}/share/man\$"; then
    NEED_MANPATH_HINT=true
  fi
fi

if $NEED_PATH_HINT; then
  cat <<SNIP

Add ~/.local/bin to your PATH (recommended):
  echo 'export PATH="\$HOME/.local/bin:\$PATH"' >> ~/.bashrc
  source ~/.bashrc
SNIP
fi

# Bash completion hint (optional, Bash-only)
if [[ -f "$SHARE_DIR/completions/smartcancel.bash" ]]; then
  cat <<'SNIP'

Enable Bash completion (current shell):
  source "${HOME}/.local/share/smartslurmcommands/completions/smartcancel.bash"

Persist completion (append to ~/.bashrc):
  if [ -f "${HOME}/.local/share/smartslurmcommands/completions/smartcancel.bash" ]; then
    source "${HOME}/.local/share/smartslurmcommands/completions/smartcancel.bash"
  fi
SNIP
fi

if $NEED_MANPATH_HINT; then
  cat <<SNIP

Make per-user man pages discoverable (optional):
  echo 'export MANPATH="${PREFIX}/share/man:${MANPATH:-}"' >> ~/.bashrc
  source ~/.bashrc

Then you can run:
  man smartcancel
SNIP
fi

# ---------- Quick smoke tests (non-fatal) ----------
echo
if [[ -x "$BIN_DIR/mqpwd" ]]; then
  echo "==> Smoke test: $BIN_DIR/mqpwd (no args)"
  "$BIN_DIR/mqpwd" >/dev/null 2>&1 || true
fi
if [[ -x "$BIN_DIR/smartcancel" ]]; then
  echo "==> Smoke test: $BIN_DIR/smartcancel --help"
  "$BIN_DIR/smartcancel" --help >/dev/null 2>&1 || true
fi

echo "Installation complete into $PREFIX."
